### ISSUE TITLE
Is the funlen repo still maintained?

### ISSUE THREAD

**Issue by martialblog** [ultraware/funlen#15]
Hey, just wanted to ask if the repo is still being maintained?

Regards
Markus

**Comment by martialblog** [comment]
If you are looking for maintainers. I could do that

**Comment by ldez** [comment]
Hi, if you (ultraware) don't want to maintain it, you can transfer the repo to golangci organization.
FYI, I'm a core maintainer of golangci-lint.

https://github.com/golangci/golangci-lint/discussions/3855

**Comment by ldez** [comment]
Hi @NiseVoid, do you know who is now in charge of this repository and [whitespace repository](https://github.com/ultraware/whitespace)?
who can we contact?

Maybe @elwint

**Comment by NiseVoid** [comment]
I don't think there's any github accounts I could mention to get you an actual answer. I've already sent this issue and the PR to them before but nothing seems to really happen. From what I've heard it gets lost in "We'll discuss it at the next X meeting".
There's an email address and contact form on their site, that could work:
https://www.ultraware.nl/nl/contact/
I'm not sure if an english version of the site is available, but there's not a lot of text so it shouldn't be hard to understand.

Forking funlen under the golangci organisation honestly doesn't seem like a bad idea, it has an MIT license so it should be quite permissive. Given their company's business model and culture, I doubt any developers would ever actively maintain the opensource repos. I also only worked on them when we found issues or when I got a mail from github about an issue or PR.

As for whitespace, it's pretty much the same. However, it might be worth considering if it's still necessary, I remember there were three linters that checked for newlines

**Comment by ldez** [comment]
@NiseVoid if we create a fork or if the linter is transferred to the golangci-lint organization are you interested to maintain it (inside our organization)?
As you are the original author it seems fair to propose that to you but I can understand if you don't want.

> As for whitespace, it's pretty much the same. However, it might be worth considering if it's still necessary, I remember there were three linters that checked for newlines

I agree whitespace feels like a duplicate, and it doesn't follow our current requirements for linter.
I need to think about that, but it is very likely that we will depreciate it.

> There's an email address and contact form on their site, 

I contacted them through the contact form.

**Comment by NiseVoid** [comment]
> @NiseVoid if we create a fork or if the linter is transferred to the golangci-lint organization are you interested to maintain it (inside our organization)?

I don't work with Go much lately so I probably wouldn't be a very active maintainer, and I think with my somewhat rusty Go knowledge maintaining a library that deals with ast would probably be difficult. So it would probably be better to have someone else maintain it, but if there's any cases where a second or third opinion is necessary you could always ping me

**Comment by martialblog** [comment]
@ldez  I could maintain the fork if you are looking for someone.

**Comment by robinknaapen** [comment]
@ldez @martialblog 

First of all, sorry for the late reply and decision making from our end.

We decided to keep the funlen linter maintenance in this organisation.
Pull requests are welcome. 

Will strive to discuss/review/maintain in a acceptable time frame in the future.

**Comment by ldez** [comment]
ok thank you :+1: 

I think you can close this issue now.

**Comment by martialblog** [comment]
Hey, thanks for the feedback. No worries, I know how it is.
