### ISSUE TITLE
Ignore comments

### ISSUE THREAD

**Issue by jadegopher** [ultraware/funlen#20]
I think comments do not add any complexity to the functions and besides provide more context and describe non obvious parts of code. 

May be it would be cool to add feature that allows ignore comment lines?

**Comment by martialblog** [comment]
Hi, 

Should already be a thing with `ignore-comments: true`

https://golangci-lint.run/usage/linters/#funlen

But maybe the README here should also reflect that.

Regards,
Markus

**Comment by robinknaapen** [comment]
Closed by #21
