### ISSUE TITLE
Installation guide error 404

### ISSUE THREAD

**Issue by EvertonMelo** [ultraware/funlen#4]
## Installation guide error 404

your link https://github.com/golangci/golangci-lint/ does not work

**Comment by NiseVoid** [comment]
Thanks for reporting this issue. It seems I had put the markdown in the wrong order, so it would try to open a file name golangci-lint instead of going to the url.

I have fixed this in 8b55b30f2b653c72cfaa8830acbe5cba8cc8de92

**Comment by EvertonMelo** [comment]
fixed
