### ISSUE TITLE
Why lint on func length? 

### ISSUE THREAD

**Issue by MaerF0x0** [ultraware/funlen#6]
In the face of some resistance to this linter being applied (and engineers just doing `nolint:funlen` whenever they want, I wonder if it might be a good idea to add a "Why?" kind of section to the readme.md .  Do you have any sources to encourage folks to use funlen? Would you be open to such a PR if I were to write it?

**Comment by NiseVoid** [comment]
This sounds like a good idea. However, I fear that the people that just put `nolint:funlen` everywhere are hard to convince. I would be open to a PR for this.

**Comment by ldez** [comment]
https://github.com/ultraware/funlen/pull/14#issuecomment-1648199107
